CREATE TABLE IF NOT EXISTS `webprostor_smtp_logs` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `DATE_CREATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ERROR_TEXT` TEXT DEFAULT NULL,
  `LOG_TEXT` TEXT DEFAULT NULL,
  `SEND_INFO` TEXT DEFAULT NULL,
  `RECIPIENTS` TEXT NOT NULL,
  `SITE_ID` char(2) NULL,
  `MODULE_ID` VARCHAR(255) NULL,
  `SENDED` CHAR(1) NOT NULL DEFAULT 'N',
  `SOURCE_TO` VARCHAR(255) DEFAULT NULL,
  `SOURCE_SUBJECT` VARCHAR(255) DEFAULT NULL,
  `SOURCE_MESSAGE` TEXT DEFAULT NULL,
  `SOURCE_HEADERS` TEXT DEFAULT NULL,
  `SOURCE_PARAMETERS` TEXT DEFAULT NULL,
  `RETRY_COUNT` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
);