<?php
use Bitrix\Main\Diag\FileExceptionHandlerLog;
use Bitrix\Main\Diag\ExceptionHandlerFormatter;
class CustomFileExceptionHandlerLog extends FileExceptionHandlerLog{
    public function write($exception, $logType)
    {
        $text = ExceptionHandlerFormatter::format($exception, false, $this->level);
        $context = [
            'type' => static::logTypeToString($logType),
        ];
        $loglevel = static::logTypeToLevel($logType);
        $message = "{date} - OTUS log -Host: {host} - {type} - {text}\n";
        $this->logger->log($loglevel, $message, $context);
//        parent::write($exception, $logType); // TODO: Change the autogenerated stub
    }
}